name: NuGet Generation

on:
  push:
    branches:
      - devpipe
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    environment:
      name: Env
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Build solution and generate NuGet package
        run: |
          cd AttributeIniFile
          dotnet build AttributeIniFile.csproj -c Release
          dotnet pack -c Release -o out AttributeIniFile.csproj 
     
      - name: echo token
        run: |
          echo $NUGET_AUTH_TOKEN 
